// Code generated by ent, DO NOT EDIT.

package ent

import (
	"placio-app/ent/comment"
	"placio-app/ent/like"
	"placio-app/ent/media"
	"placio-app/ent/post"
	"placio-app/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescContent is the schema descriptor for Content field.
	commentDescContent := commentFields[0].Descriptor()
	// comment.ContentValidator is a validator for the "Content" field. It is called by the builders before save.
	comment.ContentValidator = commentDescContent.Validators[0].(func(string) error)
	// commentDescCreatedAt is the schema descriptor for CreatedAt field.
	commentDescCreatedAt := commentFields[1].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for UpdatedAt field.
	commentDescUpdatedAt := commentFields[2].Descriptor()
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the UpdatedAt field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	likeFields := schema.Like{}.Fields()
	_ = likeFields
	// likeDescCreatedAt is the schema descriptor for CreatedAt field.
	likeDescCreatedAt := likeFields[0].Descriptor()
	// like.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	like.DefaultCreatedAt = likeDescCreatedAt.Default.(func() time.Time)
	// likeDescUpdatedAt is the schema descriptor for UpdatedAt field.
	likeDescUpdatedAt := likeFields[1].Descriptor()
	// like.UpdateDefaultUpdatedAt holds the default value on update for the UpdatedAt field.
	like.UpdateDefaultUpdatedAt = likeDescUpdatedAt.UpdateDefault.(func() time.Time)
	mediaFields := schema.Media{}.Fields()
	_ = mediaFields
	// mediaDescCreatedAt is the schema descriptor for CreatedAt field.
	mediaDescCreatedAt := mediaFields[2].Descriptor()
	// media.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	media.DefaultCreatedAt = mediaDescCreatedAt.Default.(func() time.Time)
	// mediaDescUpdatedAt is the schema descriptor for UpdatedAt field.
	mediaDescUpdatedAt := mediaFields[3].Descriptor()
	// media.DefaultUpdatedAt holds the default value on creation for the UpdatedAt field.
	media.DefaultUpdatedAt = mediaDescUpdatedAt.Default.(func() time.Time)
	// media.UpdateDefaultUpdatedAt holds the default value on update for the UpdatedAt field.
	media.UpdateDefaultUpdatedAt = mediaDescUpdatedAt.UpdateDefault.(func() time.Time)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescContent is the schema descriptor for Content field.
	postDescContent := postFields[0].Descriptor()
	// post.ContentValidator is a validator for the "Content" field. It is called by the builders before save.
	post.ContentValidator = postDescContent.Validators[0].(func(string) error)
	// postDescCreatedAt is the schema descriptor for CreatedAt field.
	postDescCreatedAt := postFields[1].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for UpdatedAt field.
	postDescUpdatedAt := postFields[2].Descriptor()
	// post.UpdateDefaultUpdatedAt holds the default value on update for the UpdatedAt field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
}
