FROM tiangolo/uvicorn-gunicorn:python3.11

ARG DB_CONNECTION
ARG MODE

ENV MODULE_NAME="africa_insight.main"
ENV VARIABLE_NAME="app"


ENV SQLALCHEMY_DATABASE_URI=${DB_CONNECTION}
ENV MODE=${MODE}

COPY ./requirements/dev.txt ./requirements/base.txt ./
RUN pip install -r dev.txt

WORKDIR /app
