// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"placio-app/ent/accountwallet"
	"placio-app/ent/booking"
	"placio-app/ent/businessfollowuser"
	"placio-app/ent/category"
	"placio-app/ent/categoryassignment"
	"placio-app/ent/comment"
	"placio-app/ent/event"
	"placio-app/ent/help"
	"placio-app/ent/like"
	"placio-app/ent/menu"
	"placio-app/ent/notification"
	"placio-app/ent/order"
	"placio-app/ent/place"
	"placio-app/ent/placetable"
	"placio-app/ent/plan"
	"placio-app/ent/post"
	"placio-app/ent/rating"
	"placio-app/ent/reservation"
	"placio-app/ent/reservationblock"
	"placio-app/ent/review"
	"placio-app/ent/staff"
	"placio-app/ent/subscription"
	"placio-app/ent/ticket"
	"placio-app/ent/trainer"
	"placio-app/ent/transactionhistory"
	"placio-app/ent/user"
	"placio-app/ent/userbusiness"
	"placio-app/ent/userfollowbusiness"
	"placio-app/ent/userfollowevent"
	"placio-app/ent/userfollowplace"
	"placio-app/ent/userfollowuser"
	"placio-app/ent/userlikeplace"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auth0/go-auth0/management"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetAuth0ID sets the "auth0_id" field.
func (uc *UserCreate) SetAuth0ID(s string) *UserCreate {
	uc.mutation.SetAuth0ID(s)
	return uc
}

// SetName sets the "name" field.
func (uc *UserCreate) SetName(s string) *UserCreate {
	uc.mutation.SetName(s)
	return uc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uc *UserCreate) SetNillableName(s *string) *UserCreate {
	if s != nil {
		uc.SetName(*s)
	}
	return uc
}

// SetPicture sets the "picture" field.
func (uc *UserCreate) SetPicture(s string) *UserCreate {
	uc.mutation.SetPicture(s)
	return uc
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (uc *UserCreate) SetNillablePicture(s *string) *UserCreate {
	if s != nil {
		uc.SetPicture(*s)
	}
	return uc
}

// SetCoverImage sets the "cover_image" field.
func (uc *UserCreate) SetCoverImage(s string) *UserCreate {
	uc.mutation.SetCoverImage(s)
	return uc
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (uc *UserCreate) SetNillableCoverImage(s *string) *UserCreate {
	if s != nil {
		uc.SetCoverImage(*s)
	}
	return uc
}

// SetUsername sets the "username" field.
func (uc *UserCreate) SetUsername(s string) *UserCreate {
	uc.mutation.SetUsername(s)
	return uc
}

// SetWebsite sets the "website" field.
func (uc *UserCreate) SetWebsite(s string) *UserCreate {
	uc.mutation.SetWebsite(s)
	return uc
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (uc *UserCreate) SetNillableWebsite(s *string) *UserCreate {
	if s != nil {
		uc.SetWebsite(*s)
	}
	return uc
}

// SetLocation sets the "location" field.
func (uc *UserCreate) SetLocation(s string) *UserCreate {
	uc.mutation.SetLocation(s)
	return uc
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (uc *UserCreate) SetNillableLocation(s *string) *UserCreate {
	if s != nil {
		uc.SetLocation(*s)
	}
	return uc
}

// SetMapCoordinates sets the "map_coordinates" field.
func (uc *UserCreate) SetMapCoordinates(m map[string]interface{}) *UserCreate {
	uc.mutation.SetMapCoordinates(m)
	return uc
}

// SetLongitude sets the "longitude" field.
func (uc *UserCreate) SetLongitude(s string) *UserCreate {
	uc.mutation.SetLongitude(s)
	return uc
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (uc *UserCreate) SetNillableLongitude(s *string) *UserCreate {
	if s != nil {
		uc.SetLongitude(*s)
	}
	return uc
}

// SetLatitude sets the "latitude" field.
func (uc *UserCreate) SetLatitude(s string) *UserCreate {
	uc.mutation.SetLatitude(s)
	return uc
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (uc *UserCreate) SetNillableLatitude(s *string) *UserCreate {
	if s != nil {
		uc.SetLatitude(*s)
	}
	return uc
}

// SetBio sets the "bio" field.
func (uc *UserCreate) SetBio(s string) *UserCreate {
	uc.mutation.SetBio(s)
	return uc
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (uc *UserCreate) SetNillableBio(s *string) *UserCreate {
	if s != nil {
		uc.SetBio(*s)
	}
	return uc
}

// SetAuth0Data sets the "auth0_data" field.
func (uc *UserCreate) SetAuth0Data(m *management.User) *UserCreate {
	uc.mutation.SetAuth0Data(m)
	return uc
}

// SetAppSettings sets the "app_settings" field.
func (uc *UserCreate) SetAppSettings(m map[string]interface{}) *UserCreate {
	uc.mutation.SetAppSettings(m)
	return uc
}

// SetUserSettings sets the "user_settings" field.
func (uc *UserCreate) SetUserSettings(m map[string]interface{}) *UserCreate {
	uc.mutation.SetUserSettings(m)
	return uc
}

// SetSearchText sets the "search_text" field.
func (uc *UserCreate) SetSearchText(s string) *UserCreate {
	uc.mutation.SetSearchText(s)
	return uc
}

// SetNillableSearchText sets the "search_text" field if the given value is not nil.
func (uc *UserCreate) SetNillableSearchText(s *string) *UserCreate {
	if s != nil {
		uc.SetSearchText(*s)
	}
	return uc
}

// SetRelevanceScore sets the "relevance_score" field.
func (uc *UserCreate) SetRelevanceScore(f float64) *UserCreate {
	uc.mutation.SetRelevanceScore(f)
	return uc
}

// SetNillableRelevanceScore sets the "relevance_score" field if the given value is not nil.
func (uc *UserCreate) SetNillableRelevanceScore(f *float64) *UserCreate {
	if f != nil {
		uc.SetRelevanceScore(*f)
	}
	return uc
}

// SetFollowerCount sets the "follower_count" field.
func (uc *UserCreate) SetFollowerCount(i int) *UserCreate {
	uc.mutation.SetFollowerCount(i)
	return uc
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (uc *UserCreate) SetNillableFollowerCount(i *int) *UserCreate {
	if i != nil {
		uc.SetFollowerCount(*i)
	}
	return uc
}

// SetFollowingCount sets the "following_count" field.
func (uc *UserCreate) SetFollowingCount(i int) *UserCreate {
	uc.mutation.SetFollowingCount(i)
	return uc
}

// SetNillableFollowingCount sets the "following_count" field if the given value is not nil.
func (uc *UserCreate) SetNillableFollowingCount(i *int) *UserCreate {
	if i != nil {
		uc.SetFollowingCount(*i)
	}
	return uc
}

// SetRole sets the "role" field.
func (uc *UserCreate) SetRole(u user.Role) *UserCreate {
	uc.mutation.SetRole(u)
	return uc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (uc *UserCreate) SetNillableRole(u *user.Role) *UserCreate {
	if u != nil {
		uc.SetRole(*u)
	}
	return uc
}

// SetPermissions sets the "permissions" field.
func (uc *UserCreate) SetPermissions(s []string) *UserCreate {
	uc.mutation.SetPermissions(s)
	return uc
}

// SetIsPremium sets the "is_premium" field.
func (uc *UserCreate) SetIsPremium(b bool) *UserCreate {
	uc.mutation.SetIsPremium(b)
	return uc
}

// SetNillableIsPremium sets the "is_premium" field if the given value is not nil.
func (uc *UserCreate) SetNillableIsPremium(b *bool) *UserCreate {
	if b != nil {
		uc.SetIsPremium(*b)
	}
	return uc
}

// SetID sets the "id" field.
func (uc *UserCreate) SetID(s string) *UserCreate {
	uc.mutation.SetID(s)
	return uc
}

// AddUserBusinessIDs adds the "userBusinesses" edge to the UserBusiness entity by IDs.
func (uc *UserCreate) AddUserBusinessIDs(ids ...string) *UserCreate {
	uc.mutation.AddUserBusinessIDs(ids...)
	return uc
}

// AddUserBusinesses adds the "userBusinesses" edges to the UserBusiness entity.
func (uc *UserCreate) AddUserBusinesses(u ...*UserBusiness) *UserCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddUserBusinessIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (uc *UserCreate) AddCommentIDs(ids ...string) *UserCreate {
	uc.mutation.AddCommentIDs(ids...)
	return uc
}

// AddComments adds the "comments" edges to the Comment entity.
func (uc *UserCreate) AddComments(c ...*Comment) *UserCreate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uc.AddCommentIDs(ids...)
}

// AddLikeIDs adds the "likes" edge to the Like entity by IDs.
func (uc *UserCreate) AddLikeIDs(ids ...string) *UserCreate {
	uc.mutation.AddLikeIDs(ids...)
	return uc
}

// AddLikes adds the "likes" edges to the Like entity.
func (uc *UserCreate) AddLikes(l ...*Like) *UserCreate {
	ids := make([]string, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return uc.AddLikeIDs(ids...)
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (uc *UserCreate) AddPostIDs(ids ...string) *UserCreate {
	uc.mutation.AddPostIDs(ids...)
	return uc
}

// AddPosts adds the "posts" edges to the Post entity.
func (uc *UserCreate) AddPosts(p ...*Post) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddPostIDs(ids...)
}

// AddFollowedUserIDs adds the "followedUsers" edge to the UserFollowUser entity by IDs.
func (uc *UserCreate) AddFollowedUserIDs(ids ...string) *UserCreate {
	uc.mutation.AddFollowedUserIDs(ids...)
	return uc
}

// AddFollowedUsers adds the "followedUsers" edges to the UserFollowUser entity.
func (uc *UserCreate) AddFollowedUsers(u ...*UserFollowUser) *UserCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddFollowedUserIDs(ids...)
}

// AddFollowerUserIDs adds the "followerUsers" edge to the UserFollowUser entity by IDs.
func (uc *UserCreate) AddFollowerUserIDs(ids ...string) *UserCreate {
	uc.mutation.AddFollowerUserIDs(ids...)
	return uc
}

// AddFollowerUsers adds the "followerUsers" edges to the UserFollowUser entity.
func (uc *UserCreate) AddFollowerUsers(u ...*UserFollowUser) *UserCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddFollowerUserIDs(ids...)
}

// AddFollowedBusinessIDs adds the "followedBusinesses" edge to the UserFollowBusiness entity by IDs.
func (uc *UserCreate) AddFollowedBusinessIDs(ids ...string) *UserCreate {
	uc.mutation.AddFollowedBusinessIDs(ids...)
	return uc
}

// AddFollowedBusinesses adds the "followedBusinesses" edges to the UserFollowBusiness entity.
func (uc *UserCreate) AddFollowedBusinesses(u ...*UserFollowBusiness) *UserCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddFollowedBusinessIDs(ids...)
}

// AddFollowerBusinessIDs adds the "followerBusinesses" edge to the BusinessFollowUser entity by IDs.
func (uc *UserCreate) AddFollowerBusinessIDs(ids ...string) *UserCreate {
	uc.mutation.AddFollowerBusinessIDs(ids...)
	return uc
}

// AddFollowerBusinesses adds the "followerBusinesses" edges to the BusinessFollowUser entity.
func (uc *UserCreate) AddFollowerBusinesses(b ...*BusinessFollowUser) *UserCreate {
	ids := make([]string, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uc.AddFollowerBusinessIDs(ids...)
}

// AddReviewIDs adds the "reviews" edge to the Review entity by IDs.
func (uc *UserCreate) AddReviewIDs(ids ...string) *UserCreate {
	uc.mutation.AddReviewIDs(ids...)
	return uc
}

// AddReviews adds the "reviews" edges to the Review entity.
func (uc *UserCreate) AddReviews(r ...*Review) *UserCreate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uc.AddReviewIDs(ids...)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (uc *UserCreate) AddBookingIDs(ids ...string) *UserCreate {
	uc.mutation.AddBookingIDs(ids...)
	return uc
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (uc *UserCreate) AddBookings(b ...*Booking) *UserCreate {
	ids := make([]string, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uc.AddBookingIDs(ids...)
}

// AddReservationIDs adds the "reservations" edge to the Reservation entity by IDs.
func (uc *UserCreate) AddReservationIDs(ids ...string) *UserCreate {
	uc.mutation.AddReservationIDs(ids...)
	return uc
}

// AddReservations adds the "reservations" edges to the Reservation entity.
func (uc *UserCreate) AddReservations(r ...*Reservation) *UserCreate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uc.AddReservationIDs(ids...)
}

// AddHelpIDs adds the "helps" edge to the Help entity by IDs.
func (uc *UserCreate) AddHelpIDs(ids ...string) *UserCreate {
	uc.mutation.AddHelpIDs(ids...)
	return uc
}

// AddHelps adds the "helps" edges to the Help entity.
func (uc *UserCreate) AddHelps(h ...*Help) *UserCreate {
	ids := make([]string, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return uc.AddHelpIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (uc *UserCreate) AddCategoryIDs(ids ...string) *UserCreate {
	uc.mutation.AddCategoryIDs(ids...)
	return uc
}

// AddCategories adds the "categories" edges to the Category entity.
func (uc *UserCreate) AddCategories(c ...*Category) *UserCreate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uc.AddCategoryIDs(ids...)
}

// AddPlaceIDs adds the "places" edge to the Place entity by IDs.
func (uc *UserCreate) AddPlaceIDs(ids ...string) *UserCreate {
	uc.mutation.AddPlaceIDs(ids...)
	return uc
}

// AddPlaces adds the "places" edges to the Place entity.
func (uc *UserCreate) AddPlaces(p ...*Place) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddPlaceIDs(ids...)
}

// AddCategoryAssignmentIDs adds the "categoryAssignments" edge to the CategoryAssignment entity by IDs.
func (uc *UserCreate) AddCategoryAssignmentIDs(ids ...string) *UserCreate {
	uc.mutation.AddCategoryAssignmentIDs(ids...)
	return uc
}

// AddCategoryAssignments adds the "categoryAssignments" edges to the CategoryAssignment entity.
func (uc *UserCreate) AddCategoryAssignments(c ...*CategoryAssignment) *UserCreate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uc.AddCategoryAssignmentIDs(ids...)
}

// SetOwnedEventsID sets the "ownedEvents" edge to the Event entity by ID.
func (uc *UserCreate) SetOwnedEventsID(id string) *UserCreate {
	uc.mutation.SetOwnedEventsID(id)
	return uc
}

// SetNillableOwnedEventsID sets the "ownedEvents" edge to the Event entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableOwnedEventsID(id *string) *UserCreate {
	if id != nil {
		uc = uc.SetOwnedEventsID(*id)
	}
	return uc
}

// SetOwnedEvents sets the "ownedEvents" edge to the Event entity.
func (uc *UserCreate) SetOwnedEvents(e *Event) *UserCreate {
	return uc.SetOwnedEventsID(e.ID)
}

// AddUserFollowEventIDs adds the "userFollowEvents" edge to the UserFollowEvent entity by IDs.
func (uc *UserCreate) AddUserFollowEventIDs(ids ...string) *UserCreate {
	uc.mutation.AddUserFollowEventIDs(ids...)
	return uc
}

// AddUserFollowEvents adds the "userFollowEvents" edges to the UserFollowEvent entity.
func (uc *UserCreate) AddUserFollowEvents(u ...*UserFollowEvent) *UserCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddUserFollowEventIDs(ids...)
}

// AddFollowedPlaceIDs adds the "followedPlaces" edge to the UserFollowPlace entity by IDs.
func (uc *UserCreate) AddFollowedPlaceIDs(ids ...string) *UserCreate {
	uc.mutation.AddFollowedPlaceIDs(ids...)
	return uc
}

// AddFollowedPlaces adds the "followedPlaces" edges to the UserFollowPlace entity.
func (uc *UserCreate) AddFollowedPlaces(u ...*UserFollowPlace) *UserCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddFollowedPlaceIDs(ids...)
}

// AddLikedPlaceIDs adds the "likedPlaces" edge to the UserLikePlace entity by IDs.
func (uc *UserCreate) AddLikedPlaceIDs(ids ...string) *UserCreate {
	uc.mutation.AddLikedPlaceIDs(ids...)
	return uc
}

// AddLikedPlaces adds the "likedPlaces" edges to the UserLikePlace entity.
func (uc *UserCreate) AddLikedPlaces(u ...*UserLikePlace) *UserCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddLikedPlaceIDs(ids...)
}

// AddRatingIDs adds the "ratings" edge to the Rating entity by IDs.
func (uc *UserCreate) AddRatingIDs(ids ...string) *UserCreate {
	uc.mutation.AddRatingIDs(ids...)
	return uc
}

// AddRatings adds the "ratings" edges to the Rating entity.
func (uc *UserCreate) AddRatings(r ...*Rating) *UserCreate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uc.AddRatingIDs(ids...)
}

// AddTransactionHistoryIDs adds the "transaction_histories" edge to the TransactionHistory entity by IDs.
func (uc *UserCreate) AddTransactionHistoryIDs(ids ...string) *UserCreate {
	uc.mutation.AddTransactionHistoryIDs(ids...)
	return uc
}

// AddTransactionHistories adds the "transaction_histories" edges to the TransactionHistory entity.
func (uc *UserCreate) AddTransactionHistories(t ...*TransactionHistory) *UserCreate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uc.AddTransactionHistoryIDs(ids...)
}

// AddReservationBlockIDs adds the "reservation_blocks" edge to the ReservationBlock entity by IDs.
func (uc *UserCreate) AddReservationBlockIDs(ids ...string) *UserCreate {
	uc.mutation.AddReservationBlockIDs(ids...)
	return uc
}

// AddReservationBlocks adds the "reservation_blocks" edges to the ReservationBlock entity.
func (uc *UserCreate) AddReservationBlocks(r ...*ReservationBlock) *UserCreate {
	ids := make([]string, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uc.AddReservationBlockIDs(ids...)
}

// AddNotificationIDs adds the "notifications" edge to the Notification entity by IDs.
func (uc *UserCreate) AddNotificationIDs(ids ...string) *UserCreate {
	uc.mutation.AddNotificationIDs(ids...)
	return uc
}

// AddNotifications adds the "notifications" edges to the Notification entity.
func (uc *UserCreate) AddNotifications(n ...*Notification) *UserCreate {
	ids := make([]string, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return uc.AddNotificationIDs(ids...)
}

// SetWalletID sets the "wallet" edge to the AccountWallet entity by ID.
func (uc *UserCreate) SetWalletID(id string) *UserCreate {
	uc.mutation.SetWalletID(id)
	return uc
}

// SetNillableWalletID sets the "wallet" edge to the AccountWallet entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableWalletID(id *string) *UserCreate {
	if id != nil {
		uc = uc.SetWalletID(*id)
	}
	return uc
}

// SetWallet sets the "wallet" edge to the AccountWallet entity.
func (uc *UserCreate) SetWallet(a *AccountWallet) *UserCreate {
	return uc.SetWalletID(a.ID)
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (uc *UserCreate) AddOrderIDs(ids ...string) *UserCreate {
	uc.mutation.AddOrderIDs(ids...)
	return uc
}

// AddOrders adds the "orders" edges to the Order entity.
func (uc *UserCreate) AddOrders(o ...*Order) *UserCreate {
	ids := make([]string, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return uc.AddOrderIDs(ids...)
}

// AddTablesCreatedIDs adds the "tables_created" edge to the PlaceTable entity by IDs.
func (uc *UserCreate) AddTablesCreatedIDs(ids ...string) *UserCreate {
	uc.mutation.AddTablesCreatedIDs(ids...)
	return uc
}

// AddTablesCreated adds the "tables_created" edges to the PlaceTable entity.
func (uc *UserCreate) AddTablesCreated(p ...*PlaceTable) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddTablesCreatedIDs(ids...)
}

// AddTablesUpdatedIDs adds the "tables_updated" edge to the PlaceTable entity by IDs.
func (uc *UserCreate) AddTablesUpdatedIDs(ids ...string) *UserCreate {
	uc.mutation.AddTablesUpdatedIDs(ids...)
	return uc
}

// AddTablesUpdated adds the "tables_updated" edges to the PlaceTable entity.
func (uc *UserCreate) AddTablesUpdated(p ...*PlaceTable) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddTablesUpdatedIDs(ids...)
}

// AddTablesDeletedIDs adds the "tables_deleted" edge to the PlaceTable entity by IDs.
func (uc *UserCreate) AddTablesDeletedIDs(ids ...string) *UserCreate {
	uc.mutation.AddTablesDeletedIDs(ids...)
	return uc
}

// AddTablesDeleted adds the "tables_deleted" edges to the PlaceTable entity.
func (uc *UserCreate) AddTablesDeleted(p ...*PlaceTable) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddTablesDeletedIDs(ids...)
}

// AddTablesReservedIDs adds the "tables_reserved" edge to the PlaceTable entity by IDs.
func (uc *UserCreate) AddTablesReservedIDs(ids ...string) *UserCreate {
	uc.mutation.AddTablesReservedIDs(ids...)
	return uc
}

// AddTablesReserved adds the "tables_reserved" edges to the PlaceTable entity.
func (uc *UserCreate) AddTablesReserved(p ...*PlaceTable) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddTablesReservedIDs(ids...)
}

// AddTablesWaitedIDs adds the "tables_waited" edge to the PlaceTable entity by IDs.
func (uc *UserCreate) AddTablesWaitedIDs(ids ...string) *UserCreate {
	uc.mutation.AddTablesWaitedIDs(ids...)
	return uc
}

// AddTablesWaited adds the "tables_waited" edges to the PlaceTable entity.
func (uc *UserCreate) AddTablesWaited(p ...*PlaceTable) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddTablesWaitedIDs(ids...)
}

// AddStaffIDs adds the "staffs" edge to the Staff entity by IDs.
func (uc *UserCreate) AddStaffIDs(ids ...string) *UserCreate {
	uc.mutation.AddStaffIDs(ids...)
	return uc
}

// AddStaffs adds the "staffs" edges to the Staff entity.
func (uc *UserCreate) AddStaffs(s ...*Staff) *UserCreate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return uc.AddStaffIDs(ids...)
}

// AddCreatedMenuIDs adds the "created_menus" edge to the Menu entity by IDs.
func (uc *UserCreate) AddCreatedMenuIDs(ids ...string) *UserCreate {
	uc.mutation.AddCreatedMenuIDs(ids...)
	return uc
}

// AddCreatedMenus adds the "created_menus" edges to the Menu entity.
func (uc *UserCreate) AddCreatedMenus(m ...*Menu) *UserCreate {
	ids := make([]string, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return uc.AddCreatedMenuIDs(ids...)
}

// AddUpdatedMenuIDs adds the "updated_menus" edge to the Menu entity by IDs.
func (uc *UserCreate) AddUpdatedMenuIDs(ids ...string) *UserCreate {
	uc.mutation.AddUpdatedMenuIDs(ids...)
	return uc
}

// AddUpdatedMenus adds the "updated_menus" edges to the Menu entity.
func (uc *UserCreate) AddUpdatedMenus(m ...*Menu) *UserCreate {
	ids := make([]string, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return uc.AddUpdatedMenuIDs(ids...)
}

// AddPlanIDs adds the "plans" edge to the Plan entity by IDs.
func (uc *UserCreate) AddPlanIDs(ids ...string) *UserCreate {
	uc.mutation.AddPlanIDs(ids...)
	return uc
}

// AddPlans adds the "plans" edges to the Plan entity.
func (uc *UserCreate) AddPlans(p ...*Plan) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddPlanIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (uc *UserCreate) AddSubscriptionIDs(ids ...string) *UserCreate {
	uc.mutation.AddSubscriptionIDs(ids...)
	return uc
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (uc *UserCreate) AddSubscriptions(s ...*Subscription) *UserCreate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return uc.AddSubscriptionIDs(ids...)
}

// AddTrainerIDs adds the "trainers" edge to the Trainer entity by IDs.
func (uc *UserCreate) AddTrainerIDs(ids ...string) *UserCreate {
	uc.mutation.AddTrainerIDs(ids...)
	return uc
}

// AddTrainers adds the "trainers" edges to the Trainer entity.
func (uc *UserCreate) AddTrainers(t ...*Trainer) *UserCreate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uc.AddTrainerIDs(ids...)
}

// AddMemberOfIDs adds the "memberOf" edge to the Place entity by IDs.
func (uc *UserCreate) AddMemberOfIDs(ids ...string) *UserCreate {
	uc.mutation.AddMemberOfIDs(ids...)
	return uc
}

// AddMemberOf adds the "memberOf" edges to the Place entity.
func (uc *UserCreate) AddMemberOf(p ...*Place) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddMemberOfIDs(ids...)
}

// AddCustomerIDs adds the "customer" edge to the Place entity by IDs.
func (uc *UserCreate) AddCustomerIDs(ids ...string) *UserCreate {
	uc.mutation.AddCustomerIDs(ids...)
	return uc
}

// AddCustomer adds the "customer" edges to the Place entity.
func (uc *UserCreate) AddCustomer(p ...*Place) *UserCreate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return uc.AddCustomerIDs(ids...)
}

// AddPurchasedTicketIDs adds the "purchasedTickets" edge to the Ticket entity by IDs.
func (uc *UserCreate) AddPurchasedTicketIDs(ids ...string) *UserCreate {
	uc.mutation.AddPurchasedTicketIDs(ids...)
	return uc
}

// AddPurchasedTickets adds the "purchasedTickets" edges to the Ticket entity.
func (uc *UserCreate) AddPurchasedTickets(t ...*Ticket) *UserCreate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return uc.AddPurchasedTicketIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if err := uc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UserCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UserCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *UserCreate) defaults() error {
	if _, ok := uc.mutation.CoverImage(); !ok {
		v := user.DefaultCoverImage
		uc.mutation.SetCoverImage(v)
	}
	if _, ok := uc.mutation.Bio(); !ok {
		v := user.DefaultBio
		uc.mutation.SetBio(v)
	}
	if _, ok := uc.mutation.FollowerCount(); !ok {
		v := user.DefaultFollowerCount
		uc.mutation.SetFollowerCount(v)
	}
	if _, ok := uc.mutation.FollowingCount(); !ok {
		v := user.DefaultFollowingCount
		uc.mutation.SetFollowingCount(v)
	}
	if _, ok := uc.mutation.Role(); !ok {
		v := user.DefaultRole
		uc.mutation.SetRole(v)
	}
	if _, ok := uc.mutation.IsPremium(); !ok {
		v := user.DefaultIsPremium
		uc.mutation.SetIsPremium(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (uc *UserCreate) check() error {
	if _, ok := uc.mutation.Auth0ID(); !ok {
		return &ValidationError{Name: "auth0_id", err: errors.New(`ent: missing required field "User.auth0_id"`)}
	}
	if _, ok := uc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "User.username"`)}
	}
	if _, ok := uc.mutation.FollowerCount(); !ok {
		return &ValidationError{Name: "follower_count", err: errors.New(`ent: missing required field "User.follower_count"`)}
	}
	if _, ok := uc.mutation.FollowingCount(); !ok {
		return &ValidationError{Name: "following_count", err: errors.New(`ent: missing required field "User.following_count"`)}
	}
	if _, ok := uc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "User.role"`)}
	}
	if v, ok := uc.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if _, ok := uc.mutation.IsPremium(); !ok {
		return &ValidationError{Name: "is_premium", err: errors.New(`ent: missing required field "User.is_premium"`)}
	}
	if v, ok := uc.mutation.ID(); ok {
		if err := user.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "User.id": %w`, err)}
		}
	}
	return nil
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected User.ID type: %T", _spec.ID.Value)
		}
	}
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeString))
	)
	if id, ok := uc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uc.mutation.Auth0ID(); ok {
		_spec.SetField(user.FieldAuth0ID, field.TypeString, value)
		_node.Auth0ID = value
	}
	if value, ok := uc.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := uc.mutation.Picture(); ok {
		_spec.SetField(user.FieldPicture, field.TypeString, value)
		_node.Picture = value
	}
	if value, ok := uc.mutation.CoverImage(); ok {
		_spec.SetField(user.FieldCoverImage, field.TypeString, value)
		_node.CoverImage = value
	}
	if value, ok := uc.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := uc.mutation.Website(); ok {
		_spec.SetField(user.FieldWebsite, field.TypeString, value)
		_node.Website = value
	}
	if value, ok := uc.mutation.Location(); ok {
		_spec.SetField(user.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := uc.mutation.MapCoordinates(); ok {
		_spec.SetField(user.FieldMapCoordinates, field.TypeJSON, value)
		_node.MapCoordinates = value
	}
	if value, ok := uc.mutation.Longitude(); ok {
		_spec.SetField(user.FieldLongitude, field.TypeString, value)
		_node.Longitude = value
	}
	if value, ok := uc.mutation.Latitude(); ok {
		_spec.SetField(user.FieldLatitude, field.TypeString, value)
		_node.Latitude = value
	}
	if value, ok := uc.mutation.Bio(); ok {
		_spec.SetField(user.FieldBio, field.TypeString, value)
		_node.Bio = value
	}
	if value, ok := uc.mutation.Auth0Data(); ok {
		_spec.SetField(user.FieldAuth0Data, field.TypeJSON, value)
		_node.Auth0Data = value
	}
	if value, ok := uc.mutation.AppSettings(); ok {
		_spec.SetField(user.FieldAppSettings, field.TypeJSON, value)
		_node.AppSettings = value
	}
	if value, ok := uc.mutation.UserSettings(); ok {
		_spec.SetField(user.FieldUserSettings, field.TypeJSON, value)
		_node.UserSettings = value
	}
	if value, ok := uc.mutation.SearchText(); ok {
		_spec.SetField(user.FieldSearchText, field.TypeString, value)
		_node.SearchText = value
	}
	if value, ok := uc.mutation.RelevanceScore(); ok {
		_spec.SetField(user.FieldRelevanceScore, field.TypeFloat64, value)
		_node.RelevanceScore = value
	}
	if value, ok := uc.mutation.FollowerCount(); ok {
		_spec.SetField(user.FieldFollowerCount, field.TypeInt, value)
		_node.FollowerCount = value
	}
	if value, ok := uc.mutation.FollowingCount(); ok {
		_spec.SetField(user.FieldFollowingCount, field.TypeInt, value)
		_node.FollowingCount = value
	}
	if value, ok := uc.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := uc.mutation.Permissions(); ok {
		_spec.SetField(user.FieldPermissions, field.TypeJSON, value)
		_node.Permissions = value
	}
	if value, ok := uc.mutation.IsPremium(); ok {
		_spec.SetField(user.FieldIsPremium, field.TypeBool, value)
		_node.IsPremium = value
	}
	if nodes := uc.mutation.UserBusinessesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserBusinessesTable,
			Columns: []string{user.UserBusinessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userbusiness.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CommentsTable,
			Columns: []string{user.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LikesTable,
			Columns: []string{user.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(like.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PostsTable,
			Columns: []string{user.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.FollowedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FollowedUsersTable,
			Columns: []string{user.FollowedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfollowuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.FollowerUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FollowerUsersTable,
			Columns: []string{user.FollowerUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfollowuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.FollowedBusinessesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FollowedBusinessesTable,
			Columns: []string{user.FollowedBusinessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfollowbusiness.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.FollowerBusinessesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FollowerBusinessesTable,
			Columns: []string{user.FollowerBusinessesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(businessfollowuser.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ReviewsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewsTable,
			Columns: []string{user.ReviewsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(review.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BookingsTable,
			Columns: []string{user.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReservationsTable,
			Columns: []string{user.ReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.HelpsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HelpsTable,
			Columns: []string{user.HelpsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(help.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CategoriesTable,
			Columns: []string{user.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.PlacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.PlacesTable,
			Columns: user.PlacesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(place.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.CategoryAssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CategoryAssignmentsTable,
			Columns: []string{user.CategoryAssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categoryassignment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.OwnedEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.OwnedEventsTable,
			Columns: []string{user.OwnedEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.UserFollowEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserFollowEventsTable,
			Columns: []string{user.UserFollowEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfollowevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.FollowedPlacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FollowedPlacesTable,
			Columns: []string{user.FollowedPlacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfollowplace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.LikedPlacesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.LikedPlacesTable,
			Columns: []string{user.LikedPlacesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlikeplace.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.RatingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RatingsTable,
			Columns: []string{user.RatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rating.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.TransactionHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TransactionHistoriesTable,
			Columns: []string{user.TransactionHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transactionhistory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ReservationBlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReservationBlocksTable,
			Columns: []string{user.ReservationBlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(reservationblock.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.NotificationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.NotificationsTable,
			Columns: user.NotificationsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.WalletTable,
			Columns: []string{user.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountwallet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OrdersTable,
			Columns: []string{user.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.TablesCreatedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TablesCreatedTable,
			Columns: []string{user.TablesCreatedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(placetable.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.TablesUpdatedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TablesUpdatedTable,
			Columns: []string{user.TablesUpdatedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(placetable.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.TablesDeletedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TablesDeletedTable,
			Columns: []string{user.TablesDeletedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(placetable.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.TablesReservedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TablesReservedTable,
			Columns: []string{user.TablesReservedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(placetable.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.TablesWaitedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TablesWaitedTable,
			Columns: []string{user.TablesWaitedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(placetable.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.StaffsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.StaffsTable,
			Columns: []string{user.StaffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staff.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.CreatedMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.CreatedMenusTable,
			Columns: user.CreatedMenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.UpdatedMenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.UpdatedMenusTable,
			Columns: user.UpdatedMenusPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.PlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.PlansTable,
			Columns: user.PlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubscriptionsTable,
			Columns: []string{user.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.TrainersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.TrainersTable,
			Columns: user.TrainersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trainer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.MemberOfIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.MemberOfTable,
			Columns: user.MemberOfPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(place.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.CustomerTable,
			Columns: user.CustomerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(place.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.PurchasedTicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PurchasedTicketsTable,
			Columns: []string{user.PurchasedTicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (ucb *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*User, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UserCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
