// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Booking is the predicate function for booking builders.
type Booking func(*sql.Selector)

// Business is the predicate function for business builders.
type Business func(*sql.Selector)

// BusinessAccountSettings is the predicate function for businessaccountsettings builders.
type BusinessAccountSettings func(*sql.Selector)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Rating is the predicate function for rating builders.
type Rating func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserBusiness is the predicate function for userbusiness builders.
type UserBusiness func(*sql.Selector)
